volumes:
  - name: html-volume
    configMap:
      name: {{ my-nginx.fullname }}-html
containers:
  - name: nginx
    image: nginx:stable-alpine
    ports:
      - containerPort: 80
    volumeMounts:
      - name: html-volume
        mountPath: /usr/share/nginx/html/index.html
        subPath: index.html
