replicaCount: 2

image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

containerPort: 80

customHtml: |
  <!DOCTYPE html>
  <html>
  <head>
    <title>My Custom Page</title>
  </head>
  <body>
    <h1>Hello from My Custom HTML!</h1>
  </body>
  </html>
